#!/usr/bin/env bash

awk '
/MemTotal:/     { total = $2 }
/MemAvailable:/ { avail = $2 }
END {
    used = total - avail
    printf "%5.1f/%4.1f GiB",
           used / 1048576,
           total / 1048576
}
' /proc/meminfo
